config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

  root to: "homes#top"
  get "home/about" => "homes#about"
  get "search" => "searches#search"

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy], defaults: { format: "js" }
    get "followings" => "relationships#followings", as: "followings"
    get "followers" => "relationships#followers", as: "followers"
    get "favorited", on: :member
  end

  resources :books, only: [:index, :show, :edit, :create, :destroy, :update] do
    resource :favorites, only: [:create, :destroy], defaults: { format: "js" }
    resources :book_comments, only: [:create, :destroy], defaults: { format: "js" }
  end

  resources :chats, only: [:create, :destroy], defaults: { format: "js" }
  resources :rooms, only: [:show, :create]
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:create, :destroy, :followings, :followers]

  def create
    current_user.follow(@user)
  end

  def destroy
    current_user.unfollow(@user)
  end

  def followings
    @users = @user.followings
  end

  def followers
    @users = @user.followers
  end

  def set_user
    @user = User.find(params[:user_id])
  end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
  # Checks if two users are following each other.
  #
  # @param user_a [User] The first user.
  # @param user_b [User] The second user.
  #
  # @return [Boolean] Returns true if the two users are following each other, otherwise false.
  def mutual_following?(user_a, user_b)
    user_a.following?(user_b) && user_b.following?(user_a)
  end

  # Determines if the chat link should be displayed for the given users.
  # The chat link is shown only if the two users are not the same and they are following each other.
  #
  # @param current_user [User] The currently logged-in user.
  # @param user [User] The other user being checked.
  #
  # @return [Boolean] Returns true if the chat link should be shown, otherwise false.
  def show_chat_link?(current_user, user)
    current_user != user && mutual_following?(current_user, user)
  end
end

app/views/relationships/_btn.html.erb
<% unless current_user == user %>
  <div>
    <% if current_user.following?(user) %>
      <%= link_to user_relationships_path(user.id), method: :delete, remote: true, class: "btn btn-danger btn-sm" do %>
        <span>Unfollow</span>
      <% end %>
    <% else %>
      <%= link_to user_relationships_path(user.id), method: :post, remote: true, class: "btn btn-primary btn-sm" do %>
        <span>Follow</span>
      <% end %>
    <% end %>
  </div>
<% end %>

app/views/relationships/_followers-count.html.erb
<%= link_to user_followers_path(user) do %>
  <strong><%= user.followers.size %></strong> Followers
<% end %>

app/views/relationships/_followings-count.html.erb
<%= link_to user_followings_path(user) do %>
  <strong><%= user.followings.size %></strong> Following
<% end %>

app/views/relationships/_follows.html.erb
<section class="mb-4">
  <% if @users.exists? %>
    <%= render "users/index", users: @users, heading: heading %>
  <% else %>
    <h2><%= heading %></h2>
    <p>There are no users.</p>
  <% end %>
</section>

app/views/relationships/create.js.erb
{
  $(`#follow-<%= @user.id %>`).html(`<%= j(render "relationships/btn", user: @user) %>`);

  <%= render "relationships/js/update-count", user: @user %>
  <%= render "relationships/js/update-count", user: current_user %>
}

app/views/relationships/destroy.js.erb
{
  $(`#follow-<%= @user.id %>`).html(`<%= j(render "relationships/btn", user: @user) %>`);

  <%= render "relationships/js/update-count", user: @user %>
  <%= render "relationships/js/update-count", user: current_user %>
}

app/views/relationships/followers.html.erb
<%= render "layouts/frame", type: :full do %>
  <%= render "relationships/follows", users: @users, heading: "Follower Users" %>
<% end %>

app/views/relationships/followings.html.erb
<%= render "layouts/frame", type: :full do %>
  <%= render "relationships/follows", users: @users, heading: "Follow Users" %>
<% end %>