config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

  root to: "homes#top"
  get "home/about" => "homes#about"
  get "search" => "searches#search"

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy], defaults: { format: "js" }
    get "followings" => "relationships#followings", as: "followings"
    get "followers" => "relationships#followers", as: "followers"
    get "favorited", on: :member
  end

  resources :books, only: [:index, :show, :edit, :create, :destroy, :update] do
    resource :favorites, only: [:create, :destroy], defaults: { format: "js" }
    resources :book_comments, only: [:create, :destroy], defaults: { format: "js" }
  end

  resources :chats, only: [:create, :destroy], defaults: { format: "js" }
  resources :rooms, only: [:show, :create]
end

app/models/user.rb
class User < ApplicationRecord
  include Searchable

  GUEST_USER_EMAIL = "guest@example.com"

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :view_counts, dependent: :destroy

  has_many :favorited_books, through: :favorites, source: :book

  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  has_many :followings, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  has_many :chats, dependent: :destroy
  has_many :entries, dependent: :destroy

  validates :name, uniqueness: true, length: { in: 2..20 }
  validates :introduction, length: { maximum: 50 }

  scope :with_details, -> { includes(:followings, :followers, profile_image_attachment: :blob) }

  def get_profile_image
    (profile_image.attached?) ? profile_image : "default-user-icon.jpeg"
  end

  def follow(user)
    unless following?(user)
      active_relationships.create(followed_id: user.id)
    end
  end

  def unfollow(user)
    if following?(user)
      active_relationships.find_by(followed_id: user.id).destroy
    end
  end

  def following?(user)
    followings.include?(user)
    # followings.any? { |following| following.id == user.id }
  end

  def chat_data(other_user)
    self_user_entry = Entry.where(user_id: self.id)
    other_user_entry = Entry.where(user_id: other_user.id)

    current_room_id = find_common_room_id(self_user_entry, other_user_entry)

    if current_room_id
      { room_id: current_room_id }
    else
      {
        room: Room.new,
        entry: Entry.new
      }
    end
  end

  def guest_user?
    email == GUEST_USER_EMAIL
  end

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "Guest User"
    end
  end

  private
  # Finds the common room ID shared between two users based on their entries.
  # If no common room exists, returns nil.
  #
  # @param user_a_entries [Entry] Entries related to the first user.
  # @param user_b_entries [Entry] Entries related to the second user.
  #
  # @return [Integer, nil] Returns the ID of the common room if found, otherwise nil.
  def find_common_room_id(user_a_entries, user_b_entries)
    user_a_entries.pluck(:room_id).each do |a_room_id|
      return a_room_id if user_b_entries.exists?(room_id: a_room_id)
    end

    nil
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: "Logged in as Guest User."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]
  before_action :ensure_guest_user, only: [:edit]
  before_action :set_user, only: [:show, :edit, :posted, :favorited, :update]

  rescue_from ActiveRecord::RecordNotFound do |e|
    redirect_to users_path
  end

  def index
    @users = User.with_details
    @user = current_user
  end

  def show
    @books = @user.books.with_details
  end

  def edit
  end

  def favorited
    @books = @user.favorited_books.with_details
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def ensure_correct_user
    user = User.find(params[:id])
    unless user == current_user
      redirect_to user_path(current_user)
    end
  end

  def ensure_guest_user
    user = User.find(params[:id])
    if user.guest_user?
      redirect_to user_path(current_user), alert: "Guest users cannot go to the edit profile page."
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_details.html.erb
<section class="mb-4">
  <h2>User info</h2>

  <div class="user-profile my-4">
    <div class="text-center"><%= image_tag user.get_profile_image, size: "128x128" %></div>
    <div class="font-weight-bold h5 my-2"><%= user.name %></div>
    <div><%= user.introduction %></div>
    <div class="user-followings-count" data-user-id="<%= user.id %>">
      <%= render "relationships/followings-count", user: user %>
    </div>
    <div class="user-followers-count" data-user-id="<%= user.id %>">
      <%= render "relationships/followers-count", user: user %>
    </div>
  </div>

  <% unless user.guest_user? %>
    <% if user == current_user %>
      <div class="text-center">
        <%= link_to edit_user_path(user), class: "mx-auto btn btn-sm btn-outline-secondary px-4" do %>
          <i class="fa-solid fa-user-gear"></i>
        <% end %>
      </div>
    <% else %>
      <div class="d-flex flex-wrap justify-content-around align-items-center mx-auto" id="follow-<%= user.id %>">
        <%= render "relationships/btn", user: user %>
        <%= render "rooms/btn", user: user %>
      </div>
    <% end %>
  <% end %>
</section>

app/views/users/_form.html.erb
<section class="mb-4">
  <h2><%= heading %></h2>
  <div class="form-body">
    <%= form_with model: user, local: true do |f| %>
      <div class="form-group">
        <%= f.label :name, class: "font-weight-bold" %>
        <%= f.text_field :name, class: "form-control", autofocus: true, placeholder: "Enter your name" %>
      </div>

      <div class="form-group">
        <%= f.label :image, class: "font-weight-bold" %>
        <%= f.file_field :profile_image, class: "form-control-file", accept: "image/*" %>
      </div>

      <div class="form-group">
        <%= f.label :introduction, class: "font-weight-bold" %>
        <%= f.text_area :introduction, class: "form-control", rows: "3", placeholder: "Enter your self-introduction" %>
      </div>

      <% if action == :update %>
        <div class="form-group">
          <%= f.button :type => "submit", class: "btn btn-primary" do %>
            Update User
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
</section>

app/views/users/_index.html.erb
<section class="mb-4">
  <h2><%= heading %></h2>
  <div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th data-col="avatar">Image</th>
          <th data-col="name">Name</th>
          <th data-col="rest" colspan="4"></th>
        </tr>
      </thead>
      <tbody>
        <%= render partial: "users/row", collection: users, as: :user %>
      </tbody>
    </table>
  </div>
</section>

app/views/users/_posted-books.html.erb
<% if user %>
  <%= render partial: "books/index", locals: {
    heading: "Books",
    books: user.books,
    empty_message: empty_index_text(user)
  } %>
<% end %>

app/views/users/_row.html.erb
<tr>
  <td data-col="avatar">
    <%= image_tag user.get_profile_image, size: "48x48" %>
  </td>
  <td data-col="name">
    <%= user.name %>
  </td>
  <td data-col="followings">
    <div class="user-followings-count" data-user-id="<%= user.id %>">
      <%= render "relationships/followings-count", user: user %>
    </div>
  </td>
  <td data-col="followers">
    <div class="user-followers-count" data-user-id="<%= user.id %>">
      <%= render "relationships/followers-count", user: user %>
    </div>
  </td>
  <td data-col="follow-btn">
    <div id="follow-<%= user.id %>">
      <%= render "relationships/btn", user: user %>
    </div>
  </td>
  <td data-col="show">
    <%= link_to "Show", user %>
  </td>
</tr>

app/views/users/_show.html.erb
<div class="d-flex my-2">
  <div class="w-25">
    <%= render "users/tab-button", path: user_path(user), isactive: page == :books do %>
      Books
    <% end %>
  </div>
  <div class="w-25">
    <%= render "users/tab-button", path: favorited_user_path(user), isactive: page == :favorited do %>
      Favorited
    <% end %>
  </div>
</div>
<div id="books-<%= user.id %>">
  <%= render partial: "books/index", locals: {
    heading: page.capitalize,
    books: books,
    empty_message: empty_index_text(user, page)
  } %>
</div>

app/views/users/_tab-button.html.erb
<% class_name = "btn #{isactive ? "btn-primary" : "btn-outline-secondary"} btn-block border-1 rounded-0" %>
<%= link_to path, class: class_name do %>
  <%= yield %>
<% end %>

app/views/users/edit.html.erb
<%= render "layouts/errors", model: @user %>
<%= render "layouts/frame", type: :medium do %>
  <%= render "users/form", user: @user, heading: "User info", action: :update %>
<% end %>

app/views/users/favorited.html.erb
<%= render "layouts/frame", user: @user, type: :sidebar do %>
  <%= render "users/show", user: @user, books: @books, page: :favorited %>
<% end %>

app/views/users/index.html.erb
<%= render "layouts/frame", user: @user, type: :sidebar do %>
  <%= render "users/index", users: @users, heading: "Users" %>
<% end %>

app/views/users/show.html.erb
<%= render "layouts/frame", user: @user, type: :sidebar do %>
  <%= render "users/show", user: @user, books: @books, page: :books %>
<% end %>